# Generated by Django 5.0.1 on 2024-02-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0006_sign_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign_up',
            name='username',
            field=models.CharField(default='default_username', max_length=100),
        ),
        migrations.AlterField(
            model_name='sign_up',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
