# Generated by Django 5.0.1 on 2024-02-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0007_sign_up_username_alter_sign_up_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign_up',
            name='password',
            field=models.CharField(default='password', max_length=100),
        ),
        migrations.AlterField(
            model_name='sign_up',
            name='username',
            field=models.CharField(default='Username', max_length=100),
        ),
    ]
