# Generated by Django 5.0.1 on 2024-02-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0008_sign_up_password_alter_sign_up_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sign_UP',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='Username', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Username', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Username', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='Username', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='Username', max_length=50),
        ),
    ]
